# Modules
- color: "fbca04"
  description: "This issue or pull request is related to dx-connection module."
  name: ":floppy_disk: dx-connection"
- color: "fbca04"
  description: "This issue or pull request is related to dx-gateway module."
  name: ":floppy_disk: dx-gateway"
- color: "fbca04"
  description: "This issue or pull request is related to dx-private-virtual-interface module."
  name: ":floppy_disk: dx-private-virtual-interface"
- color: "fbca04"
  description: "This issue or pull request is related to lattice-alb-target-group module."
  name: ":floppy_disk: lattice-alb-target-group"
- color: "fbca04"
  description: "This issue or pull request is related to lattice-instance-target-group module."
  name: ":floppy_disk: lattice-instance-target-group"
- color: "fbca04"
  description: "This issue or pull request is related to lattice-ip-target-group module."
  name: ":floppy_disk: lattice-ip-target-group"
- color: "fbca04"
  description: "This issue or pull request is related to lattice-lambda-target-group module."
  name: ":floppy_disk: lattice-lambda-target-group"
- color: "fbca04"
  description: "This issue or pull request is related to lattice-service module."
  name: ":floppy_disk: lattice-service"
- color: "fbca04"
  description: "This issue or pull request is related to lattice-service-listener module."
  name: ":floppy_disk: lattice-service-listener"
- color: "fbca04"
  description: "This issue or pull request is related to lattice-service-network module."
  name: ":floppy_disk: lattice-service-network"
- color: "fbca04"
  description: "This issue or pull request is related to lattice-shared-service module."
  name: ":floppy_disk: lattice-shared-service"
- color: "fbca04"
  description: "This issue or pull request is related to lattice-shared-service-network module."
  name: ":floppy_disk: lattice-shared-service-network"
- color: "fbca04"
  description: "This issue or pull request is related to reachability-analyzer-path module."
  name: ":floppy_disk: reachability-analyzer-path"
