# Modules
":floppy_disk: dx-connection":
- changed-files:
  - any-glob-to-any-file:
    - modules/dx-connection/**/*

":floppy_disk: dx-gateway":
- changed-files:
  - any-glob-to-any-file:
    - modules/dx-gateway/**/*

":floppy_disk: dx-private-virtual-interface":
- changed-files:
  - any-glob-to-any-file:
    - modules/dx-private-virtual-interface/**/*

":floppy_disk: reachability-analyzer-path":
- changed-files:
  - any-glob-to-any-file:
    - modules/reachability-analyzer-path/**/*
